-- Version: $Revision$
-- Source: $Source$
-- Date: $Date$
-- Author: $Author$

DELETE FROM REFERENCEKEYWORDRELATIONSHIPS;
DELETE FROM FILES;
DELETE FROM ANNOTATIONS;
DELETE FROM LINKS;
DELETE FROM BOOKS;
DELETE FROM FORMALPUBLICATIONS;
DELETE FROM REFERENCESTABLE;
