INSERT INTO REFERENCESTABLE (KEYID,NAME,HASHVALUE,DESCRIPTION,VERSION,INCOMPLETE,WHENINSERTED,DOCUMENTDATE,OPTIMISTICLOCKINGVERSION) VALUES (1,'Beginning Jsp 2.0',null,'Build Web Applications Using Jsp, Java, and Struts.',null,0,{ts '2008-08-13 14:43:38.692'},null,0);
INSERT INTO REFERENCESTABLE (KEYID,NAME,HASHVALUE,DESCRIPTION,VERSION,INCOMPLETE,WHENINSERTED,DOCUMENTDATE,OPTIMISTICLOCKINGVERSION) VALUES (4,'The LaTeX Companion',null,'Provides expert advice on using Latex''s basic formatting tools for creating all types of publications. Includes in-depth coverage of important extension packages for tabular and technical typesetting.',null,0,{ts '2008-08-13 14:46:44.628'},null,0);
INSERT INTO REFERENCESTABLE (KEYID,NAME,HASHVALUE,DESCRIPTION,VERSION,INCOMPLETE,WHENINSERTED,DOCUMENTDATE,OPTIMISTICLOCKINGVERSION) VALUES (3,'Design Patterns: Elements of Reusable Object-Oriented Software',null,'The classic book for design patterns.',null,0,{ts '2008-08-13 14:45:08.864'},null,0);
INSERT INTO REFERENCESTABLE (KEYID,NAME,HASHVALUE,DESCRIPTION,VERSION,INCOMPLETE,WHENINSERTED,DOCUMENTDATE,OPTIMISTICLOCKINGVERSION) VALUES (5,'Java In A Nutshell',null,'"The" book for Java developers',null,0,{ts '2008-08-13 14:48:55.807'},null,0);

INSERT INTO FORMALPUBLICATIONS (KEYTOREFERENCE,AUTHORNAME,PUBLISHER,PAGENUM) VALUES (1,null,null,0);
INSERT INTO FORMALPUBLICATIONS (KEYTOREFERENCE,AUTHORNAME,PUBLISHER,PAGENUM) VALUES (3,null,null,0);
INSERT INTO FORMALPUBLICATIONS (KEYTOREFERENCE,AUTHORNAME,PUBLISHER,PAGENUM) VALUES (4,null,null,0);
INSERT INTO FORMALPUBLICATIONS (KEYTOREFERENCE,AUTHORNAME,PUBLISHER,PAGENUM) VALUES (5,null,null,0);

INSERT INTO BOOKS (KEYTOREFERENCE,AUTHORNAME,PUBLISHER,PAGENUM,ISBNNUMBER) VALUES (1,null,null,null,null);
INSERT INTO BOOKS (KEYTOREFERENCE,AUTHORNAME,PUBLISHER,PAGENUM,ISBNNUMBER) VALUES (3,null,null,null,null);
INSERT INTO BOOKS (KEYTOREFERENCE,AUTHORNAME,PUBLISHER,PAGENUM,ISBNNUMBER) VALUES (4,null,null,null,null);
INSERT INTO BOOKS (KEYTOREFERENCE,AUTHORNAME,PUBLISHER,PAGENUM,ISBNNUMBER) VALUES (5,null,null,null,null);