./dep.sh jboss-common.jar	org.jboss	jboss-common
./dep.sh jboss-el-api.jar	org.jboss.el	jboss-el-api
./dep.sh jboss-el.jar	org.jboss.el	jboss-el
./dep.sh jboss-seam-debug.jar	org.jboss.seam	jboss-seam-debug
./dep.sh jboss-seam-ui.jar	org.jboss.seam	jboss-seam-ui
./dep.sh jboss-seam.jar	org.jboss.seam	jboss-seam
./dep.sh thirdparty-all.jar	org.jboss.seam	thirdparty-all
./dep.sh jsf-api.jar	javax.faces	jsf-api
./dep.sh jsf-impl.jar	javax.faces	jsf-impl
./dep.sh jsf-facelets.jar	com.sun.facelets	jsf-facelets
./dep.sh richfaces-api-3.1.1-SNAPSHOT.jar	org.richfaces	richfaces-api
./dep.sh richfaces-impl-3.1.1-SNAPSHOT.jar	org.richfaces	richfaces-impl
./dep.sh richfaces-ui-3.1.1-SNAPSHOT.jar	org.richfaces	richfaces-ui
