CREATE TABLE addresses (
  addressid INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  address1 VARCHAR(64) UNIQUE NOT NULL,
  address2  VARCHAR(64) UNIQUE NOT NULL
)