CREATE INDEX i_bpbparel_bp_key ON ABC
(BP_KEY ASC)
LOGGING
TABLESPACE  TBL_SPC
PCTFREE     10
INITRANS    2
MAXTRANS    255
STORAGE (
        INITIAL       65536
        MINEXTENTS    1
        MAXEXTENTS    2147483645
        PCTINCREASE   0
        BUFFER_POOL   DEFAULT
        )
NOPARALLEL
;

CREATE INDEX i_bpbparel_bpa_key ON DEF
(BPAGENT_KEY ASC)
LOGGING
TABLESPACE  TBL_SPC
PCTFREE     10
INITRANS    2
MAXTRANS    255
STORAGE (
        INITIAL       65536
        MINEXTENTS    1
        MAXEXTENTS    2147483645
        PCTINCREASE   0
        BUFFER_POOL   DEFAULT
        )
NOPARALLEL
;