/* Create Tables */
CREATE TABLE ABC
(
	KEYID                       NUMBER(10) NOT NULL,
	OPTIMISTIC_LOCKING_VERSION  NUMBER(10) DEFAULT 0,
	ID                          VARCHAR2(50 CHAR) NOT NULL,
	NAME                        VARCHAR2(100 CHAR) NOT NULL,
	ROLES                       VARCHAR2(30 CHAR)
)
TABLESPACE  TBL_SPC
PCTUSED     0
PCTFREE     10
INITRANS    1
MAXTRANS    255
STORAGE (
        INITIAL         65536
        MINEXTENTS      1
        MAXEXTENTS      2147483645
        PCTINCREASE     0
        BUFFER_POOL     DEFAULT
        )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;


CREATE TABLE DEF
(
	BP_KEY       NUMBER(10) NOT NULL,
	BPAGENT_KEY  NUMBER(10) NOT NULL
)
TABLESPACE  TBL_SPC
PCTUSED     0
PCTFREE     10
INITRANS    1
MAXTRANS    255
STORAGE (
        INITIAL         65536
        MINEXTENTS      1
        MAXEXTENTS      2147483645
        PCTINCREASE     0
        BUFFER_POOL     DEFAULT
        )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;


CREATE TABLE GHI
(
	KEYID                       NUMBER(10) NOT NULL,
	OPTIMISTIC_LOCKING_VERSION  NUMBER(10) DEFAULT 0,
	ABORT_URL                   VARCHAR2(1000 CHAR) NOT NULL,
	ERROR_URL                   VARCHAR2(1000 CHAR) NOT NULL,
	SUCCESSION_URL              VARCHAR2(1000 CHAR) NOT NULL,
	TIMEOUT_URL                 VARCHAR2(1000 CHAR) NOT NULL,
	TICKET_PROCEDURE_KEY        NUMBER(10) NOT NULL
)
TABLESPACE  TBL_SPC
PCTUSED     0
PCTFREE     10
INITRANS    1
MAXTRANS    255
STORAGE (
        INITIAL         65536
        MINEXTENTS      1
        MAXEXTENTS      2147483645
        PCTINCREASE     0
        BUFFER_POOL     DEFAULT
        )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;


CREATE TABLE JKL
(
	KEYID                       NUMBER(10) NOT NULL,
	OPTIMISTIC_LOCKING_VERSION  NUMBER(10) DEFAULT 0,
	CSS_URL                     VARCHAR2(1000 CHAR) NOT NULL,
	ID                          VARCHAR2(50 CHAR) NOT NULL,
	NAME                        VARCHAR2(100 CHAR) NOT NULL
)
TABLESPACE  TBL_SPC
PCTUSED     0
PCTFREE     10
INITRANS    1
MAXTRANS    255
STORAGE (
        INITIAL         65536
        MINEXTENTS      1
        MAXEXTENTS      2147483645
        PCTINCREASE     0
        BUFFER_POOL     DEFAULT
        )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;


CREATE TABLE MNO
(
	KEYID                       NUMBER(10) NOT NULL,
	OPTIMISTIC_LOCKING_VERSION  NUMBER(10) DEFAULT 0,
	ADDRESS                     VARCHAR2(200 CHAR),
	EMAIL                       VARCHAR2(100 CHAR),
	IP                          VARCHAR2(15 CHAR),
	NAME                        VARCHAR2(100 CHAR) NOT NULL,
	TELEPHONE                   VARCHAR2(50 CHAR),
	TICKET_PROCEDURE_KEY        NUMBER(10) NOT NULL
)
TABLESPACE  TBL_SPC
PCTUSED     0
PCTFREE     10
INITRANS    1
MAXTRANS    255
STORAGE (
        INITIAL         65536
        MINEXTENTS      1
        MAXEXTENTS      2147483645
        PCTINCREASE     0
        BUFFER_POOL     DEFAULT
        )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

