/* Create Primary Key Constraints */
ALTER TABLE ABC ADD CONSTRAINT pk_bpa 
	PRIMARY KEY (KEYID)
;

ALTER TABLE DEF ADD CONSTRAINT pk_bpn 
	PRIMARY KEY (KEYID)
;

ALTER TABLE GHI ADD CONSTRAINT fk_tpl_tp 
	FOREIGN KEY (PROCEDURE_KEY) REFERENCES TEST_PROCEDURE (KEYID)
;

ALTER TABLE JKL
	ADD CONSTRAINT bp_bpa_uq UNIQUE (BP_KEY, BPAGENT_KEY)
;

/* Create Indexes */
ALTER TABLE MNO
	ADD CONSTRAINT olv_bpa CHECK (optimistic_locking_version>=0)
;