CREATE TABLE contacts (
  contactid INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  firstname VARCHAR(64) UNIQUE NOT NULL,
  lastname  VARCHAR(64) UNIQUE NOT NULL,
  address VARCHAR(64) UNIQUE NOT NULL,
  city VARCHAR(64) UNIQUE NOT NULL
);