-- Create script for local schema.
-- This file is read and executed by the test starter.

-- USE LOCAL;

-- Oracle key ranges: 1 - 2147483647 remote, 2147483648 - 4294967295 local
-- (this is 1 <-> 2^31-1 and 2^31 <-> 2^32-1)

CREATE SEQUENCE simpleperson_sequence INCREMENT BY 1 START WITH 2147483648 MINVALUE 2147483648 MAXVALUE 4294967295;
CREATE SEQUENCE person_sequence INCREMENT BY 1 START WITH 2147483648 MINVALUE 2147483648 MAXVALUE 4294967295;

CREATE TABLE SIMPLEPERSON (
    ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL
);

CREATE TABLE PERSON (
	ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	PARENT BIGINT REFERENCES PERSON(ID)
);

-- The offliner tables.

CREATE SEQUENCE keymap_sequence INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE properties_sequence INCREMENT BY 1 START WITH 1;

CREATE TABLE KEYMAP (
	ID INT NOT NULL PRIMARY KEY,    
	LOCALBASEVERSION VARCHAR(128) NOT NULL,
	REMOTEBASEVERSION VARCHAR(128) NOT NULL,
	DELETEVERSION BIGINT NOT NULL,
	SYNCVERSION INT,
    LOCALKEY VARCHAR(128) NOT NULL,
    REMOTEKEY VARCHAR(128) NOT NULL
);

CREATE TABLE OFFLINERPROPERTIES (
	ID INT NOT NULL PRIMARY KEY,
	PROPNAME VARCHAR(30) NOT NULL UNIQUE,
    PROPVALUE VARCHAR(40)
);