-- Comment
/* single line comment */
CREATE TABLE keywords (
  keyId                     INTEGER        NOT NULL 
    GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)
    PRIMARY KEY,
  name                      VARCHAR(64)    UNIQUE NOT NULL,
  description               VARCHAR(256),
  optimisticLockingVersion  INTEGER        NOT NULL
);
/* another comment...
... ending in a valid line */INSERT INTO /* intermediate comment */ KEYWORDS (KEYID,NAME,DESCRIPTION,OPTIMISTICLOCKINGVERSION) VALUES (1,'Java','A title with
multiple
lines',0);
/* multi
line
comment:
CREATE TABLE keywords (
  keyId                     INTEGER        NOT NULL 
    GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)
    PRIMARY KEY,
  name                      VARCHAR(64)    UNIQUE NOT NULL,
  description               VARCHAR(256),
  optimisticLockingVersion  INTEGER        NOT NULL
);*/

/* end */